### ISSUE TITLE
Remove c: attribute references in DOM

### ISSUE THREAD

**Issue by evilchia** [cydran/cydran#125] opened 2019-11-12 07:22 UTC
c:model (and perhaps other c: attribute references) still appear in HTML

Expectation that c: attributes are sanitized

<img width="428" alt="Screen Shot 2019-11-12 at 00 06 17" src="https://user-images.githubusercontent.com/1290008/68649793-c60abf80-04e0-11ea-9692-879f9806464f.png">

**Comment by matthewwerny** [comment] 2019-11-12 07:25
This is a duplicate of #114

**Closed by matthewwerny** 2019-11-12 07:25 UTC
Labels: bug
